package main

import (
	"bufio"
	"io"
)

// EqualFunc ...
type EqualFunc func(s1 string, s2 string) bool

// UniqScanner ...
type UniqScanner struct {
	scanner *bufio.Scanner
	first   bool
	last    bool
	prev    string
	this    string
	text    string
	repeats int
	equal   EqualFunc
}

// NewScanner return a new UniqScanner to read from r.
func NewScanner(r io.Reader) *UniqScanner {
	scanner := &UniqScanner{
		scanner: bufio.NewScanner(r),
		first:   true,
		last:    true,
		equal: func(s1 string, s2 string) bool {
			return s1 == s2
		},
	}
	return scanner
}

// Scan advances the Scanner to the next token.
func (u *UniqScanner) Scan() bool {
	if u.first {
		u.first = false
		if u.scanner.Scan() {
			u.prev = u.scanner.Text()
			u.text = u.prev
			return true
		}
		return false
	}

	for u.scanner.Scan() {
		u.this = u.scanner.Text()
		if !u.equal(u.prev, u.this) {
			u.prev = u.this
			u.text = u.prev
			return true
		}
		u.repeats++
	}

	return false
}

// ScanDuplicate advances the Scanner to the next token.
func (u *UniqScanner) ScanDuplicate() bool {
	if u.first {
		u.first = false
		if u.scanner.Scan() {
			u.prev = u.scanner.Text()
		}
	}

	for u.scanner.Scan() {
		u.this = u.scanner.Text()
		if !u.equal(u.prev, u.this) {
			if u.repeats != 0 {
				u.text = u.prev
				u.prev = u.this
				u.repeats = 0
				return true
			}
			u.prev = u.this
			u.repeats = 0
		} else {
			u.repeats++
		}
	}

	if u.last {
		u.last = false
		if u.repeats != 0 {
			u.text = u.prev
			return true
		}
	}

	return false
}

// ScanUnique advances the Scanner to the next token.
func (u *UniqScanner) ScanUnique() bool {
	if u.first {
		u.first = false
		if u.scanner.Scan() {
			u.prev = u.scanner.Text()
		}
	}

	for u.scanner.Scan() {
		u.this = u.scanner.Text()
		if !u.equal(u.prev, u.this) {
			if u.repeats == 0 {
				u.text = u.prev
				u.prev = u.this
				return true
			}
			u.prev = u.this
			u.repeats = 0
		} else {
			u.repeats++
		}
	}

	if u.last {
		u.last = false
		if u.repeats == 0 {
			u.text = u.prev
			return true
		}
	}

	return false
}

// Equal sets the equal function for the UniqScanner. If called, it must be
// called before Scan/ScanDuplicate/ScanUnique.
func (u *UniqScanner) Equal(equal EqualFunc) {
	u.equal = equal
}

// Text return the most recent token generated by a call to
// Scan/ScanDuplicate/ScanUnique.
func (u *UniqScanner) Text() string {
	return u.text
}
